### ISSUE TITLE
gnome-terminal 256 color black line numbers

### ISSUE THREAD

**Issue by cmeiklejohn** [noahfrederick/vim-hemisu#1] opened 2012-02-03 16:33 UTC
Running this theme, dark version, in gnome-terminal with 256 colors renders black line numbers.

**Comment by noahfrederick** [comment] 2012-02-03 16:47
Unfortunately I'm limited to testing on Mac OS's 256-color terminal for the foreseeable future. Feel free to link me to a screenshot, if possible, and I may gain some insight. Thanks.

**Comment by cmeiklejohn** [comment] 2012-02-03 16:54
See: [Screenshot](http://corrupted.datagr.am/tmp/Selection_014.png)

**Comment by noahfrederick** [comment] 2012-02-04 01:35
Other are reporting that it displays correctly in gnome-terminal if you set background=dark _after_ setting the color scheme.

**Comment by cmeiklejohn** [comment] 2012-02-04 16:43
That corrects a bunch of weird color-related things, but does not resolve the line numbers issue.  The screenshot above is from after running set background=dark after setting the scheme.

**Comment by tupton** [comment] 2012-02-21 02:53
I have this problem, too, in iTerm 2.

I switched the values for 'almostBlack' and 'darkGrey' so that their values were a little closer to what their names say. This makes line numbers a bit more visible. See noahfrederick/Hemisu#2 for the pull request.

**Comment by tupton** [comment] 2012-02-21 05:48
@cmeiklejohn My pull request was merged. I think you'll find that line numbers show up now.

**Comment by cmeiklejohn** [comment] 2012-02-21 17:52
Visible, but still very difficult to read.  Thanks.

**Comment by tupton** [comment] 2012-02-21 17:59
If you're using gnome-terminal, are you using the "Tango" color scheme? I use this color scheme in iTerm 2 and I can see the line numbers (but yes, they are somewhat faint). Also, is your terminal set to display 256 colors?

```
$ export TERM=xterm 
$ tput colors
8
$ export TERM=xterm-256color
$ tput colors
256
```

Put `export TERM=xterm-256color` somewhere in your `.bashrc` to enable 256 colors.

Of course, you may know all of this already. I admit, the line numbers are indeed pretty faint. I kind of like it, but if you want to change them, perhaps you could change `s:subtle` on line 127 ("NonText") to something different, like `s:dimmed`.

**Comment by cmeiklejohn** [comment] 2012-02-21 18:02
I'm in 256 colors, and I'm using whatever the default color scheme is, I assume something like clearlooks, as I'm using xmonad with the xfce bindings.  I've also verified that it looks the same in both gnome-terminal and terminator.  I'll try going the route of changing the line numbers color.

**Comment by noahfrederick** [comment] 2012-02-22 14:09
I was able to verify that the line numbers were still pretty faint in gnome-terminal. I had a chance to mess around with it a bit. @cmeiklejohn You should find that the line numbers now display as intended (as well as comments, which I upped the brightness on a bit too).

By the way, it looks like my suggestion of setting `background` again wipes out the color scheme, so I would in fact _not_ do that. ;)

**Closed as completed by noahfrederick** 2012-02-22 14:09 UTC

**Comment by cmeiklejohn** [comment] 2012-02-22 15:58
Looks much better!  Thank you.
